# Generated by Django 3.0.6 on 2020-05-16 07:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SavingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selection_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='app.SavingType')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='app.IncomeType')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='app.ExpenseType')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=100)),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
