# Generated by Django 3.0.6 on 2020-05-16 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='expense_type',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='name',
            new_name='income_type',
        ),
    ]
